services:

  # ---------------- AUTH SERVICE ----------------
  - type: web
    name: auth-service
    env: docker
    plan: free
    dockerfilePath: ./auth-service/Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 5002
      - key: DB_HOST
        value: ep-proud-block-acxjqli5-pooler.sa-east-1.aws.neon.tech
      - key: DB_NAME
        value: vg-ms-autentication
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DATABASE_URL
        value: r2dbc:postgresql://ep-proud-block-acxjqli5-pooler.sa-east-1.aws.neon.tech:5432/vg-ms-autentication?sslmode=require
      - key: KEYCLOAK_URL
        value: https://lab.vallegrande.edu.pe/keycloak
      - key: KEYCLOAK_REALM
        value: sipreb
      - key: KEYCLOAK_CLIENT_ID
        value: sipreb-backend
      - key: KEYCLOAK_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false

  # ---------------- PATRIMONIO ----------------
  - type: web
    name: patrimonio-service
    env: docker
    plan: free
    dockerfilePath: ./patrimonio-service/Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 5003
      - key: DB_URL
        value: r2dbc:postgresql://ep-snowy-dream-ad4r62wl-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: KEYCLOAK_ISSUER_URI
        value: https://lab.vallegrande.edu.pe/keycloak/realms/sipreb

  # ---------------- API GATEWAY ----------------
  - type: web
    name: api-gateway
    env: docker
    plan: free
    dockerfilePath: ./api-gateway/Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 5000
      - key: AUTH_SERVICE_URL
        value: https://auth-service.onrender.com
      - key: PATRIMONIO_SERVICE_URL
        value: https://patrimonio-service.onrender.com